version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - db_network
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NIMBLE_API_KEY=${NIMBLE_API_KEY}
  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - db_network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./src/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  db_network:

volumes:
  postgres_data:
